### PR TITLE
Fix MapBox SSR hydration error

### LINKED ISSUE #1: Should handle SSR properly
**Describe the bug** A clear and concise description of what the bug is.

When using with SSR, there will be a warning

```txt
Warning: Expected server HTML to contain a matching <div> in <div>.
```

**To Reproduce** Steps to reproduce the behavior:

1. Run the example next.js project.
2. Go to `localhost:3000/raw`, which uses map components directly.
3. See the warning in browser's console.

**Expected behavior** A clear and concise description of what you expected to
happen.

Should handle SSR properly.

### PR DESCRIPTION
**Pull request by isBatak**
# Description

Partial fix for #1. 
Other components like `<CustomControl>` has the same problem, but that could be handled in another PR.

Fixes #1

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for your
test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lucifer1004** [comment]
This does not fix `Warning: Expected server HTML to contain a matching <div> in <div>.`

In the example next.js project, I turned off SSR via

```jsx
const Home = dynamic(() => import('../components/Map'), {
  ssr: false
})
```

If you change it into

```jsx
const Home = dynamic(() => import('../components/Map'))
```

The warning will occur.

**Comment by isBatak** [comment]
@lucifer1004 warning you see is probably 
`Warning: Expected server HTML to contain a matching <button> in <div>.`
that is related to `<CustomControl>` and usage of ReactDOM.createPortal.
If you remove `<DrawingControl />` component from `<Map/> you should see no warnings.
Two pass rendering approach should fix that issue but I didn't have time to investigate that... here are some details about it https://reactjs.org/docs/react-dom.html#hydrate

**Comment by lucifer1004** [comment]
@all-contributors please add @isBatak for code

**Comment by isBatak** [comment]
@lucifer1004 could you make a new release?

**Comment by lucifer1004** [comment]
> @lucifer1004 could you make a new release?

`0.1.11` has been published.

**Pull request merged**
